---

native_apps:
  - steam
  - discord
  - pcmanfm
  - udiskie
  - mate-calc

aur_apps:
  - steam-fonts
  - proton-ge-custom-bin
  - mangohud
  - lib32-mangohud
  - spotify
  - spotifywm-git
  - betterdiscord-installer
  - anki-official-binary-bundle
  - ani-cli-git
